//! Worker-local, host-generated bytecode only. No serialized bytecode API or
//! disk cache: every load/restart validates source and compiles with this build.
use crate::{diagnostic::Diagnostics, with_runtime, ScriptResult, BOOTSTRAP};
use rquickjs::{qjs, Ctx, FromJs, Function, Object, Value};
use sparrow_plugin::{
    script::{CacheInfo, ErrorPhase, ScriptFailure, MAX_CACHE_BYTES},
    Manifest,
};

struct Bytecode(Vec<u8>);
impl Bytecode {
    fn compile(ctx: &Ctx<'_>, source: &str) -> Result<Self, &'static str> {
        let mut input = source.as_bytes().to_vec();
        input.push(0);
        // Same global/strict/filename contract as the previous Ctx::eval.
        let flags =
            qjs::JS_EVAL_TYPE_GLOBAL | qjs::JS_EVAL_FLAG_STRICT | qjs::JS_EVAL_FLAG_COMPILE_ONLY;
        let raw = unsafe {
            qjs::JS_Eval(
                ctx.as_raw().as_ptr(),
                input.as_ptr().cast(),
                source.len() as _,
                c"eval_script".as_ptr(),
                flags as i32,
            )
        };
        if unsafe { qjs::JS_IsException(raw) } {
            return Err("compile");
        }
        // SAFETY: JS_Eval returned an owned value in this live Context.
        let compiled = unsafe { Value::from_raw(ctx.clone(), raw) };
        let mut len = 0;
        let ptr = unsafe {
            qjs::JS_WriteObject(
                ctx.as_raw().as_ptr(),
                &mut len,
                compiled.as_raw(),
                qjs::JS_WRITE_OBJ_BYTECODE as i32,
            )
        };
        if ptr.is_null() {
            return Err("compile cache");
        }
        // Always free the engine allocation, including a rejected oversize blob.
        struct Buffer<'a, 'js> {
            ctx: &'a Ctx<'js>,
            ptr: *mut u8,
        }
        impl Drop for Buffer<'_, '_> {
            fn drop(&mut self) {
                unsafe {
                    qjs::js_free(self.ctx.as_raw().as_ptr(), self.ptr.cast());
                }
            }
        }
        let _buffer = Buffer { ctx, ptr };
        if len as usize > MAX_CACHE_BYTES || len == 0 {
            return Err("cache too large");
        }
        // Retain source/debug data; don't change Function.toString or locations.
        Ok(Self(
            unsafe { std::slice::from_raw_parts(ptr, len as usize) }.to_vec(),
        ))
    }
    fn evaluate<'js>(&self, ctx: &Ctx<'js>) -> Result<Value<'js>, &'static str> {
        // SAFETY: this private Vec can only be produced by compile() above in
        // the same worker/build. Never enable SAB or arbitrary object references.
        let function = unsafe {
            qjs::JS_ReadObject(
                ctx.as_raw().as_ptr(),
                self.0.as_ptr(),
                self.0.len() as _,
                qjs::JS_READ_OBJ_BYTECODE as i32,
            )
        };
        if unsafe { qjs::JS_IsException(function) } {
            return Err("cache load");
        }
        // JS_EvalFunction consumes function (also on failure); do not wrap/free
        // that input a second time. Only the returned value is Rust-owned.
        let value = unsafe { qjs::JS_EvalFunction(ctx.as_raw().as_ptr(), function) };
        if unsafe { qjs::JS_IsException(value) } {
            return Err("execution");
        }
        Ok(unsafe { Value::from_raw(ctx.clone(), value) })
    }
}

pub struct Cache {
    bootstrap: Bytecode,
    script: Bytecode,
    source: String,
    info: CacheInfo,
}
impl Cache {
    pub fn prepare(manifest: &Manifest, source: String) -> ScriptResult<Self> {
        if !manifest.is_script() {
            return Err(ScriptFailure::plain(ErrorPhase::Compile, "kind"));
        }
        manifest
            .check_artifact(source.as_bytes())
            .map_err(|_| ScriptFailure::plain(ErrorPhase::Compile, "manifest"))?;
        with_runtime(1500, |ctx| {
            let bootstrap = Bytecode::compile(&ctx, BOOTSTRAP)
                .map_err(|e| ScriptFailure::plain(ErrorPhase::Cache, e))?;
            let stack_getter = Function::from_js(
                &ctx,
                bootstrap
                    .evaluate(&ctx)
                    .map_err(|e| ScriptFailure::plain(ErrorPhase::Runtime, e))?,
            )
            .map_err(|_| ScriptFailure::plain(ErrorPhase::Runtime, "bootstrap"))?;
            let diagnostic = Diagnostics::new(stack_getter, &source);
            let script = Bytecode::compile(&ctx, &source)
                .map_err(|e| diagnostic.capture(&ctx, ErrorPhase::Compile, e))?;
            let bytes = bootstrap.0.len().saturating_add(script.0.len());
            if bytes > MAX_CACHE_BYTES {
                return Err(ScriptFailure::plain(ErrorPhase::Cache, "cache too large"));
            }
            let value = script
                .evaluate(&ctx)
                .map_err(|e| diagnostic.capture(&ctx, ErrorPhase::Initialize, e))?;
            let object = Object::from_js(&ctx, value).map_err(|_| {
                ScriptFailure::plain(ErrorPhase::Initialize, "exports object required")
            })?;
            for def in &manifest.functions {
                object.get::<_, Function>(def.name.as_str()).map_err(|_| {
                    diagnostic.capture(&ctx, ErrorPhase::Export, "export must be callable")
                })?;
            }
            drop(object);
            drop(diagnostic);
            Ok(Self {
                bootstrap,
                script,
                source,
                info: CacheInfo {
                    artifact_sha256: manifest.artifact_sha256.clone(),
                    bytes,
                    compiled_scripts: 2,
                },
            })
        })
    }
    pub fn info(&self) -> CacheInfo {
        self.info.clone()
    }
    pub fn open<'cache, 'js>(
        &'cache self,
        ctx: &Ctx<'js>,
    ) -> ScriptResult<(Object<'js>, Diagnostics<'cache, 'js>)> {
        let value = self
            .bootstrap
            .evaluate(ctx)
            .map_err(|e| ScriptFailure::plain(ErrorPhase::Cache, e))?;
        let getter = Function::from_js(ctx, value)
            .map_err(|_| ScriptFailure::plain(ErrorPhase::Runtime, "bootstrap"))?;
        let diagnostic = Diagnostics::new(getter, &self.source);
        let value = self
            .script
            .evaluate(ctx)
            .map_err(|e| diagnostic.capture(ctx, ErrorPhase::Initialize, e))?;
        let object = Object::from_js(ctx, value)
            .map_err(|_| ScriptFailure::plain(ErrorPhase::Initialize, "exports object required"))?;
        Ok((object, diagnostic))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn scripts_cache_refuses_oversize_generated_code() {
        let result = with_runtime(1500, |ctx| {
            // Direct writer test: ordinary package source is independently 32KiB.
            let source = format!("'{}'", "x".repeat(MAX_CACHE_BYTES));
            assert!(matches!(
                Bytecode::compile(&ctx, &source),
                Err("cache too large")
            ));
            Ok(())
        });
        result.unwrap();
    }

    #[test]
    #[ignore = "explicit ABBA microbenchmark, not a throughput certification"]
    fn scripts_cache_abba_microbenchmark() {
        use crate::{input, invoke, output};
        use rquickjs::function::Args;
        use sparrow_plugin::{script::WireValue, FunctionDef, ValueType, JS_TARGET};
        use std::time::Instant;
        // Same fresh runtime, limits, bootstrap and typed function/output for
        // both paths. No IPC or process RLIMIT in this libtest microbenchmark.
        for source in ["({f(v){return v*2n;}})",
            "({f(v){const x=JSON.parse('{\"temperature\":21,\"enabled\":true}');return x.enabled?BigInt(x.temperature)*v:0n;}})"] {
            let manifest=Manifest {package:None,format:1,name:"bench".into(),version:"v1".into(),
                kind:"javascript_scalar".into(),abi:1,semantics:1,target:JS_TARGET.into(),
                artifact_sha256:sparrow_plugin::sha256(source.as_bytes()),deterministic:true,thread_safe:true,
                null_policy:"propagate".into(),functions:vec![FunctionDef{name:"f".into(),id:1,
                    inputs:vec![ValueType::Int64],output:ValueType::Int64,max_output_bytes:1}]};
            let cache=Cache::prepare(&manifest,source.into()).unwrap();
            for (round,cached) in [false,true,true,false].into_iter().enumerate() {
                let mut samples=Vec::new();
                for n in 0..2020 {
                    let start=Instant::now();
                    let value=if cached {invoke(&manifest,&cache,1,vec![WireValue::Int("21".into())]).unwrap()}
                    else {with_runtime(100,|ctx| {
                        let _:Value=ctx.eval(BOOTSTRAP).unwrap();
                        let object:Object=ctx.eval(source).unwrap();
                        let function:Function=object.get("f").unwrap();
                        let mut args=Args::new(ctx.clone(),1);
                        args.push_arg(input(WireValue::Int("21".into()),&ctx).unwrap()).unwrap();
                        let value:Value=function.call_arg(args).unwrap();
                        Ok(output(value,&manifest.functions[0]).unwrap())
                    }).unwrap()};
                    let elapsed=start.elapsed().as_nanos();
                    assert!(matches!(value,WireValue::Int(ref v) if v==if source.contains("JSON") {"441"}else{"42"}));
                    if n>=20 {samples.push(elapsed);}
                }
                samples.sort_unstable();
                eprintln!("cache_bench {}",serde_json::json!({"workload":if source.contains("JSON"){"json"}else{"bigint"},
                    "round":round,"cached":cached,"calls":samples.len(),"p50_ns":samples[1000],"p99_ns":samples[1980],
                    "mean_ns":samples.iter().sum::<u128>()/samples.len() as u128}));
            }
        }
    }
}
