// Public test-only identity generated for localhost; never use in production.
pub const CA: &[u8] = br#"-----BEGIN CERTIFICATE-----
MIIBiTCCAS+gAwIBAgIUYDMDZ42sJesUL4Af8Qufti88CmUwCgYIKoZIzj0EAwIw
GjEYMBYGA1UEAwwPU3BhcnJvdy1UZXN0LUNBMB4XDTI2MDkxMTEwMTY1MFoXDTQ2
MDkwNjEwMTY1MFowGjEYMBYGA1UEAwwPU3BhcnJvdy1UZXN0LUNBMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEo3S1TNhktkw1FA62Zz5AntTrev/M9uAa3V6xUHZ3
ZFPb/Ypy+MGmsrM+uATzX8XXzW/UkH0mKH1g6DAOTU1gh6NTMFEwHQYDVR0OBBYE
FAuZX5fbL+WsecZXXGooNjdFxoOTMB8GA1UdIwQYMBaAFAuZX5fbL+WsecZXXGoo
NjdFxoOTMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIgBhPLvpOr
FsPX7koDy7jbD1zoCH9+K8Xur3wgTTInTQoCIQD4cazSyZ2mkBUh5BS5xF/7S/Z5
QDBcCxF/DQo5RsXUXA==
-----END CERTIFICATE-----
"#;
pub const CERT: &[u8] = br#"-----BEGIN CERTIFICATE-----
MIIBgzCCASmgAwIBAgIBATAKBggqhkjOPQQDAjAaMRgwFgYDVQQDDA9TcGFycm93
LVRlc3QtQ0EwHhcNMjYwOTExMTAxNjUwWhcNNDYwOTA2MTAxNjUwWjAUMRIwEAYD
VQQDDAlsb2NhbGhvc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQNKTpKACp1
I6L6uuZ26ScZdjEQgO22dBK7XtFmAa3p4YSEKQNZyajRT00oTSoAHxYq+g+B+OFg
DXkDlYsOrmcZo2YwZDAUBgNVHREEDTALgglsb2NhbGhvc3QwDAYDVR0TAQH/BAIw
ADAdBgNVHQ4EFgQUtH9LugavOYo6DNt8MiOMHMQSUb0wHwYDVR0jBBgwFoAUC5lf
l9sv5ax5xldcaig2N0XGg5MwCgYIKoZIzj0EAwIDSAAwRQIhANq+Xrp61eiyMXzg
bCYmjvKooBrCJl47gjOTmAg4A8wCAiACgVWiUPoM/tmu+2gQX7TQjBJgvjNhqfRe
MiPoeLcuLg==
-----END CERTIFICATE-----
"#;
pub const KEY: &[u8] = br#"-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgyZQaQWl4D/5amdTo
5Qv9UU7CZd9VPAmub6r//wa7lcmhRANCAAQNKTpKACp1I6L6uuZ26ScZdjEQgO22
dBK7XtFmAa3p4YSEKQNZyajRT00oTSoAHxYq+g+B+OFgDXkDlYsOrmcZ
-----END PRIVATE KEY-----
"#;
